---
resources:
- name: pal-tracker
  type: git
  source:
    uri: {{github-repository}}
    branch: my-work
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/current-version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: allocations-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/allocations-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: backlog-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/backlog-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: registration-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/registration-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: timesheets-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: pal-tracker/timesheets-server-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: cf
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: sandbox
    skip_cert_check: true


jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params:
      bump: patch
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: allocations-artifacts
    params:
      file: build-output/allocations*.jar
  - put: backlog-artifacts
    params:
      file: build-output/backlog*.jar
  - put: registration-artifacts
    params:
      file: build-output/registration*.jar
  - put: timesheets-artifacts
    params:
      file: build-output/timesheets*.jar
  - put: version
    params:
      file: version/number

- name: deploy-allocations
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: allocations-artifacts
    trigger: false
  - task: migrate allocations database
    file: pal-tracker-distributed/ci/migrateDatabase.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: sandbox
      MYSQL_IP: {{mysql-ip}}
      DATABASE_NAME: {{tracker-allocations-database}}
      DATABASE_USERNAME: {{tracker-allocations-database-username}}
      DATABASE_PASSWORD: {{tracker-allocations-database-password}}
      DATABASE_LOCATION: allocations-database
      APP_NAME: tracker-allocations
  - put: cf
    params:
      manifest: pal-tracker/manifest-allocations.yml
      path: allocations-artifacts/allocations-server*.jar

- name: deploy-backlog
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: backlog-artifacts
    trigger: false
  - task: migrate backlog database
    file: pal-tracker-distributed/ci/migrateDatabase.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: sandbox
      MYSQL_IP: {{mysql-ip}}
      DATABASE_NAME: {{tracker-backlog-database}}
      DATABASE_USERNAME: {{tracker-backlog-database-username}}
      DATABASE_PASSWORD: {{tracker-backlog-database-password}}
      DATABASE_LOCATION: backlog-database
      APP_NAME: tracker-backlog
  - put: cf
    params:
      manifest: pal-tracker/manifest-backlog.yml
      path: backlog-artifacts/backlog-server*.jar

- name: deploy-registration
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: registration-artifacts
    trigger: false
  - task: migrate registration database
    file: pal-tracker-distributed/ci/migrateDatabase.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: sandbox
      MYSQL_IP: {{mysql-ip}}
      DATABASE_NAME: {{tracker-registration-database}}
      DATABASE_USERNAME: {{tracker-registration-database-username}}
      DATABASE_PASSWORD: {{tracker-registration-database-password}}
      DATABASE_LOCATION: registration-database
      APP_NAME: tracker-registration
  - put: cf
    params:
      manifest: pal-tracker/manifest-registration.yml
      path: registration-artifacts/registration-server*.jar

- name: deploy-timesheets
  plan:
  - get: pal-tracker
    passed: [build]
    trigger: true
  - get: timesheets-artifacts
    trigger: false
  - task: migrate timesheets database
    file: pal-tracker-distributed/ci/migrateDatabase.yml
    params:
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: {{cf-org}}
      CF_SPACE: sandbox
      MYSQL_IP: {{mysql-ip}}
      DATABASE_NAME: {{tracker-timesheets-database}}
      DATABASE_USERNAME: {{tracker-timesheets-database-username}}
      DATABASE_PASSWORD: {{tracker-timesheets-database-password}}
      DATABASE_LOCATION: timesheets-database
      APP_NAME: tracker-timesheets
  - put: cf
    params:
      manifest: pal-tracker/manifest-timesheets.yml
      path: timesheets-artifacts/timesheets-server*.jar
